version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8081:8081"
      - "6379:6379"
    links:
      - redis
    volumes:
    - logs/application-debug.log:/logs/application-debug.log
    environment:
      REDIS_PASSWORD: password
  redis:
    image: redis:6.2-alpine
    ports:
    - "6379:6379"
    command: redis-server --requirepass password
